// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swlowtmujyunabicsfmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3bG93dG11anl1bmFiaWNzZm1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNjg2ODIsImV4cCI6MjA1MzY0NDY4Mn0.am55KtCIRxowcM93PeHeOjGhyLDlPsTsklZJR_5As_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);